### ISSUE TITLE
quick action button to mark an asset as used

### ISSUE THREAD

**Issue by ryanmerolle** [ArnesSI/netbox-inventory#54] opened 2023-01-24 21:27 UTC
Add a UI quick action button to mark an asset as used from the various views without needing to go to the edit asset page.

**Comment by matejv** [comment] 2023-01-30 07:23
duplicate of #45 I believe :)

**Closed by matejv** 2023-01-30 07:23 UTC

**Comment by ryanmerolle** [comment] 2023-01-30 14:54
ha yea. I frogot.  Sorry about that.
